/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWishlistRouteImport } from './routes/app.wishlist'
import { Route as AppAddRouteImport } from './routes/app.add'
import { Route as AppProductProductIdRouteImport } from './routes/app.product.$productId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWishlistRoute = AppWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AppRoute,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const AppProductProductIdRoute = AppProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/add': typeof AppAddRoute
  '/app/wishlist': typeof AppWishlistRoute
  '/app/': typeof AppIndexRoute
  '/app/product/$productId': typeof AppProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/add': typeof AppAddRoute
  '/app/wishlist': typeof AppWishlistRoute
  '/app': typeof AppIndexRoute
  '/app/product/$productId': typeof AppProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/add': typeof AppAddRoute
  '/app/wishlist': typeof AppWishlistRoute
  '/app/': typeof AppIndexRoute
  '/app/product/$productId': typeof AppProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/search'
    | '/sitemap.xml'
    | '/app/add'
    | '/app/wishlist'
    | '/app/'
    | '/app/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/sitemap.xml'
    | '/app/add'
    | '/app/wishlist'
    | '/app'
    | '/app/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/search'
    | '/sitemap.xml'
    | '/app/add'
    | '/app/wishlist'
    | '/app/'
    | '/app/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wishlist': {
      id: '/app/wishlist'
      path: '/wishlist'
      fullPath: '/app/wishlist'
      preLoaderRoute: typeof AppWishlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/add': {
      id: '/app/add'
      path: '/add'
      fullPath: '/app/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/product/$productId': {
      id: '/app/product/$productId'
      path: '/product/$productId'
      fullPath: '/app/product/$productId'
      preLoaderRoute: typeof AppProductProductIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppWishlistRoute: typeof AppWishlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProductProductIdRoute: typeof AppProductProductIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppWishlistRoute: AppWishlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppProductProductIdRoute: AppProductProductIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
